[package]
name = "balls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.5"
nalgebra = "0.32.5"

[profile.dev.package.'*']
opt-level = 3

